### PR TITLE
Use glob instead of walkdir

### PR DESCRIPTION
**Pull request by YuriSolovyov**
Fixes https://github.com/atom/asar/issues/24

### CODE REVIEW

**Comment by YuriSolovyov** [comment]
Inspired by https://github.com/bwin/asar/commit/308d5ca

**Comment by YuriSolovyov** [comment]
should I keep walkdir for tests or make test use glob too?

**Comment by YuriSolovyov** [comment]
@zcbenz 
I moved crawler function into own file to de-dublicate things and re-used it in tests.

**Comment by zcbenz** [comment]
Looks good to me, thanks!

**Pull request merged**
