### PR TITLE
Revert "drop chromium-pickle dependency. implement reading / writing asa...

### PR DESCRIPTION
**Pull request by YuriSolovyov**
Reverts atom/asar#22
Although asar test itself are passing it completly breaks reading of asar package by atom-shell itself.
Let's revert it and find better solution.

### CODE REVIEW

**Comment by zcbenz** [comment]
I think we should rewrite chromium-pickle in JavaScript instead of hacking on Pickle's headers.

**Comment by YuriSolovyov** [comment]
well, I agree, but my skills end in js level :)
simpliest layout IMO could be
```
SIZE <- UInt32
HEADER <- UTF-8 JSON string
FILE-1 bytes
...
FILE-N bytes
```
this could be written in pure js, but we need to acess this in c++ too.
Is there way to rewrite asar support in atom-shell in pure js?

**Comment by bwin** [comment]
> Is there way to rewrite asar support in atom-shell in pure js?

I tried exacly that, but ATM I think it's not possible since we need to support asar in all situations (e.g. protocol).

> I think we should rewrite chromium-pickle in JavaScript instead of hacking on Pickle's headers.

About that, my opinion stays the same. I would really like to drop pickle (and cuint BTW) completely.
We just need it to read/write uints and a string. We only operate on little endian platforms (correct me, if I'm wrong), so no need for further abstractiion of uints on the c/c++ side. And about the string, there was no need (IMHO) for "pickling" in the first place.

**Comment by YuriSolovyov** [comment]
@zcbenz  Can we move discussion to a new issue?

**Comment by bwin** [comment]
Move it back to #16.

**Pull request merged**
